/***************************
	* jquery.counterup.min.js
	* jquery.inview.min.js
	* jpreloader.min.js
	* jquery.countdown.min.js
	* jquery.nav.min.js
	* jquery.stellar.min.js
	* responsiveslides.min.js
	* respimage.min.js
	* smoothscroll.min.js
	* bootstrap.min.js
*****************************/
(function(b){b.fn.counterUp=function(j){var l=b.extend({time:400,delay:10},j);return this.each(function(){var e=b(this);e.one("inview",function(){var a=[],c=l.time/l.delay,f=e.text(),g=/[0-9]+,[0-9]+/.test(f);f=f.replace(/,/g,"");/^[0-9]+$/.test(f);for(var h=/^[0-9]+\.[0-9]+$/.test(f),m=h?(f.split(".")[1]||[]).length:0,q=c;q>=1;q--){var x=parseInt(f/c*q);h&&(x=parseFloat(f/c*q).toFixed(m));if(g)for(;/(\d+)(\d{3})/.test(x.toString());)x=x.toString().replace(/(\d+)(\d{3})/,"$1,$2");a.unshift(x)}e.data("counterup-nums",
a);e.text("0");e.data("counterup-func",function(){e.text(e.data("counterup-nums").shift());if(e.data("counterup-nums").length)setTimeout(e.data("counterup-func"),l.delay);else{delete e.data("counterup-nums");e.data("counterup-nums",null);e.data("counterup-func",null)}});setTimeout(e.data("counterup-func"),l.delay)})})}})(jQuery);
(function(b){function j(){var e=window.innerHeight;if(e)return e;var a=document.compatMode;if(a||!b.support.boxModel)e=a==="CSS1Compat"?document.documentElement.clientHeight:document.body.clientHeight;return e}var l=function(e,a){function c(){if(g!==null)f=true;else{f=false;e();g=setTimeout(function(){g=null;f&&c()},a)}}var f=false,g=null;return c}(function(){var e=window.pageYOffset||document.documentElement.scrollTop||document.body.scrollTop,a=e+j(),c=[];b.each(b.cache,function(){this.events&&this.events.inview&&
c.push(this.handle.elem)});b(c).each(function(){var f=b(this),g;g=0;for(var h=this;h;h=h.offsetParent)g+=h.offsetTop;h=f.outerHeight();var m=g+h;h=f.data("inview")||false;var q=f.data("offset")||0,x=g>e&&m<a,H=m+q>e&&g<e;q=g-q<a&&m>a;if(x||H||q||g<e&&m>a){g=q?"top":H?"bottom":"both";if(!h||h!==g){f.data("inview",g);f.trigger("inview",[true,g])}}else if(!x&&h){f.data("inview",false);f.trigger("inview",[false])}})},100);b(window).on("checkInView.inview click.inview ready.inview scroll.inview resize.inview",
l)})(jQuery);
(function(b){var j=[],l=[],e=function(){},a=0,c={splashVPos:"35%",loaderVPos:"75%",splashID:"#jpreContent",showSplash:true,showPercentage:true,autoClose:true,closeBtnText:"Start!",onetimeLoad:false,debugMode:false,splashFunction:function(){}},f=function(y){if(c.onetimeLoad){var d=new Date;d.setDate(d.getDate()+y);y=y==null?"":"expires="+d.toUTCString();document.cookie="jpreLoader=loaded; "+y}},g=function(){jOverlay=b("<div></div>").attr("id","jpreOverlay").css({position:"fixed",top:0,left:0,width:"100%",
height:"100%",zIndex:9999999}).appendTo("body");if(c.showSplash){jContent=b("<div></div>").attr("id","jpreSlide").appendTo(jOverlay);var y=b(window).width()-b(jContent).width();b(jContent).css({position:"absolute",top:c.splashVPos,left:Math.round(50/b(window).width()*y)+"%"});b(jContent).html(b(c.splashID).wrap("<div></div>").parent().html());b(c.splashID).remove();c.splashFunction()}jLoader=b("<div></div>").attr("id","jpreLoader").appendTo(jOverlay);y=b(window).width()-b(jLoader).width();b(jLoader).css({position:"absolute",
top:c.loaderVPos,left:Math.round(50/b(window).width()*y)+"%"});jBar=b("<div></div>").attr("id","jpreBar").css({width:"0%",height:"100%"}).appendTo(jLoader);if(c.showPercentage)jPer=b("<div></div>").attr("id","jprePercentage").css({position:"relative",height:"100%"}).appendTo(jLoader).html("Loading...");c.autoclose||(jButton=b("<div></div>").attr("id","jpreButton").on("click",function(){x()}).css({position:"relative",height:"100%"}).appendTo(jLoader).text(c.closeBtnText).hide())},h=function(y){b(y).find("*:not(script)").each(function(){var d=
"";if(b(this).css("background-image").indexOf("none")==-1&&b(this).css("background-image").indexOf("-gradient")==-1){d=b(this).css("background-image");if(d.indexOf("url")!=-1)d=d.match(/url\((.*?)\)/)[1].replace(/\"/g,"")}else if(b(this).get(0).nodeName.toLowerCase()=="img"&&typeof b(this).attr("src")!="undefined")d=b(this).attr("src");d.length>0&&j.push(d)})},m=function(y){var d=new Image;b(d).load(function(){q()}).error(function(){l.push(b(this).attr("src"));q()}).attr("src",y)},q=function(){a++;
var y=Math.round(a/j.length*100);b(jBar).stop().animate({width:y+"%"},500,"linear");c.showPercentage&&b(jPer).text(y+"%");if(a>=j.length){a=j.length;f();c.showPercentage&&b(jPer).text("100%");c.debugMode&&H();b(jBar).stop().animate({width:"100%"},500,"linear",function(){c.autoClose?x():b(jButton).fadeIn(1E3)})}},x=function(){b(jOverlay).fadeOut(800,function(){b(jOverlay).remove();e()})},H=function(){if(l.length>0){var y="ERROR - IMAGE FILES MISSING!!!\n\r";y+=l.length+" image files cound not be found. \n\r";
y+="Please check your image paths and filenames:\n\r";for(var d=0;d<l.length;d++)y+="- "+l[d]+"\n\r";return true}else return false};b.fn.jpreLoader=function(y,d){y&&b.extend(c,y);if(typeof d=="function")e=d;b("body").css({display:"block"});return this.each(function(){var n;a:{if(c.onetimeLoad){n=document.cookie.split("; ");for(var k=0,v;v=n[k]&&n[k].split("=");k++)if(v.shift()==="jpreLoader"){n=v.join("=");break a}}n=false}if(n){b(c.splashID).remove();e()}else{g();h(this);if(j.length>0)for(n=0;n<
j.length;n++)m(j[n]);else q()}})}})(jQuery);
(function(b){"function"==typeof define&&define.amd?define(["jquery"],b):b(jQuery)})(function(b){function j(f){return function(g){var h=g.match(/%(-|!)?[A-Z]{1}(:[^;]+;)?/gi);if(h)for(var m=0,q=h.length;q>m;++m){var x=h[m].match(/%(-|!)?([a-zA-Z]{1})(:[^;]+;)?/),H;H=x[0].toString().replace(/([.?*+^$[\]\\(){}|-])/g,"\\$1");H=RegExp(H);var y=x[1]||"",d=x[3]||"",n=null;x=x[2];a.hasOwnProperty(x)&&(n=a[x],n=Number(f[n]));if(null!==n){if("!"===y){x=d;d="s";var k="";n=(x&&(x=x.replace(/(:|;|\s)/gi,"").split(/\,/),
1===x.length||(k=x[0],d=x[1])),1===Math.abs(n)?k:d)}""===y&&10>n&&(n="0"+n.toString());g=g.replace(H,n.toString())}}return g.replace(/%%/,"%")}}var l=[],e=[];e.push(/^[0-9]*$/.source);e.push(/([0-9]{1,2}\/){2}[0-9]{4}( [0-9]{1,2}(:[0-9]{2}){2})?/.source);e.push(/[0-9]{4}([\/\-][0-9]{1,2}){2}( [0-9]{1,2}(:[0-9]{2}){2})?/.source);e=RegExp(e.join("|"));var a={Y:"years",m:"months",w:"weeks",d:"days",D:"totalDays",H:"hours",M:"minutes",S:"seconds"},c=function(f,g,h){this.el=f;this.$el=b(f);this.interval=
null;this.offset={};this.instanceNumber=l.length;l.push(this);this.$el.data("countdown-instance",this.instanceNumber);h&&(this.$el.on("update.countdown",h),this.$el.on("stoped.countdown",h),this.$el.on("finish.countdown",h));this.setFinalDate(g);this.start()};b.extend(c.prototype,{start:function(){null!==this.interval&&clearInterval(this.interval);var f=this;this.update();this.interval=setInterval(function(){f.update.call(f)},100)},stop:function(){clearInterval(this.interval);this.interval=null;this.dispatchEvent("stoped")},
toggle:function(){this.interval?this.stop():this.start()},pause:function(){this.stop()},resume:function(){this.start()},remove:function(){this.stop.call(this);l[this.instanceNumber]=null;delete this.$el.data().countdownInstance},setFinalDate:function(f){var g=f;if(g instanceof Date)f=g;else if(String(g).match(e))f=(String(g).match(/^[0-9]*$/)&&(g=Number(g)),String(g).match(/\-/)&&(g=String(g).replace(/\-/g,"/")),new Date(g));else throw Error("Couldn't cast `"+g+"` to a date object.");this.finalDate=
f},update:function(){return 0===this.$el.closest("html").length?void this.remove():(this.totalSecsLeft=this.finalDate.getTime()-(new Date).getTime(),this.totalSecsLeft=Math.ceil(this.totalSecsLeft/1E3),this.totalSecsLeft=this.totalSecsLeft<0?0:this.totalSecsLeft,this.offset={seconds:this.totalSecsLeft%60,minutes:Math.floor(this.totalSecsLeft/60)%60,hours:Math.floor(this.totalSecsLeft/60/60)%24,days:Math.floor(this.totalSecsLeft/60/60/24)%7,totalDays:Math.floor(this.totalSecsLeft/60/60/24),weeks:Math.floor(this.totalSecsLeft/
60/60/24/7),months:Math.floor(this.totalSecsLeft/60/60/24/30),years:Math.floor(this.totalSecsLeft/60/60/24/365)},void(0===this.totalSecsLeft?(this.stop(),this.dispatchEvent("finish")):this.dispatchEvent("update")))},dispatchEvent:function(f){f=b.Event(f+".countdown");f.finalDate=this.finalDate;f.offset=b.extend({},this.offset);f.strftime=j(this.offset);this.$el.trigger(f)}});b.fn.countdown=function(){var f=Array.prototype.slice.call(arguments,0);return this.each(function(){var g=b(this).data("countdown-instance");
if(void 0!==g){g=l[g];var h=f[0];c.prototype.hasOwnProperty(h)?g[h].apply(g,f.slice(1)):null===String(h).match(/^[$A-Z_][0-9A-Z_$]*$/i)?(g.setFinalDate.call(g,h),g.start()):b.error("Method %s does not exist on jQuery.countdown".replace(/\%s/gi,h))}else new c(this,f[0],f[1])})}});
(function(b,j,l){var e=function(a,c){this.elem=a;this.$elem=b(a);this.options=c;this.metadata=this.$elem.data("plugin-options");this.$win=b(j);this.sections={};this.didScroll=false;this.$doc=b(l);this.docHeight=this.$doc.height()};e.prototype={defaults:{navItems:"a",currentClass:"current",changeHash:false,easing:"swing",filter:"",scrollSpeed:750,scrollThreshold:0.5,begin:false,end:false,scrollChange:false},init:function(){return this.config=b.extend({},this.defaults,this.options,this.metadata),this.$nav=
this.$elem.find(this.config.navItems),this.$nav=b.merge(this.$nav,b("a.one-page-nav")),""!==this.config.filter&&(this.$nav=this.$nav.filter(this.config.filter)),this.$nav.on("click.onePageNav",b.proxy(this.handleClick,this)),this.getPositions(),this.bindInterval(),this.$win.on("resize.onePageNav",b.proxy(this.getPositions,this)),this},adjustNav:function(a,c){a.$elem.find("."+a.config.currentClass).removeClass(a.config.currentClass);c.addClass(a.config.currentClass)},bindInterval:function(){var a,
c=this;c.$win.on("scroll.onePageNav",function(){c.didScroll=true});c.t=setInterval(function(){a=c.$doc.height();c.didScroll&&(c.didScroll=false,c.scrollChange());a!==c.docHeight&&(c.docHeight=a,c.getPositions())},250)},getHash:function(a){return a.attr("href").split("#")[1]},getPositions:function(){var a,c,f,g=this;g.$nav.each(function(){a=g.getHash(b(this));f=b("#"+a);f.length&&(c=f.offset().top,g.sections[a]=Math.round(c))})},getSection:function(a){var c=null,f=Math.round(this.$win.height()*this.config.scrollThreshold),
g;for(g in this.sections)this.sections[g]-f<a&&(c=g);return c},handleClick:function(a){var c=this,f=b(a.currentTarget),g=f.parent(),h="#"+c.getHash(f);g.hasClass(c.config.currentClass)||(c.config.begin&&c.config.begin(),c.adjustNav(c,g),c.unbindInterval(),c.scrollTo(h,function(){c.config.changeHash&&(j.location.hash=h);c.bindInterval();c.config.end&&c.config.end()}));a.preventDefault()},scrollChange:function(){var a,c=this.getSection(this.$win.scrollTop());null!==c&&(a=this.$elem.find('a[href$="#'+
c+'"]').parent(),a.hasClass(this.config.currentClass)||(this.adjustNav(this,a),this.config.scrollChange&&this.config.scrollChange(a)))},scrollTo:function(a,c){var f=b(a).offset().top;b("html, body").animate({scrollTop:Math.max(0,f-60)},this.config.scrollSpeed,this.config.easing,c)},unbindInterval:function(){clearInterval(this.t);this.$win.unbind("scroll.onePageNav")}};e.defaults=e.prototype.defaults;b.fn.onePageNav=function(a){return this.each(function(){(new e(this,a)).init()})}})(jQuery,window,
document);
(function(b,j,l,e){function a(d,n){this.element=d;this.options=b.extend({},f,n);this._defaults=f;this._name=c;this.init()}var c="stellar",f={scrollProperty:"scroll",positionProperty:"position",horizontalScrolling:true,verticalScrolling:true,horizontalOffset:0,verticalOffset:0,responsive:false,parallaxBackgrounds:true,parallaxElements:true,hideDistantElements:true,hideElement:function(d){d.hide()},showElement:function(d){d.show()}},g={scroll:{getLeft:function(d){return d.scrollLeft()},setLeft:function(d,n){d.scrollLeft(n)},
getTop:function(d){return d.scrollTop()},setTop:function(d,n){d.scrollTop(n)}},position:{getLeft:function(d){return parseInt(d.css("left"),10)*-1},getTop:function(d){return parseInt(d.css("top"),10)*-1}},margin:{getLeft:function(d){return parseInt(d.css("margin-left"),10)*-1},getTop:function(d){return parseInt(d.css("margin-top"),10)*-1}},transform:{getLeft:function(d){d=getComputedStyle(d[0])[m];return d!=="none"?parseInt(d.match(/(-?[0-9]+)/g)[4],10)*-1:0},getTop:function(d){d=getComputedStyle(d[0])[m];
return d!=="none"?parseInt(d.match(/(-?[0-9]+)/g)[5],10)*-1:0}}},h={position:{setLeft:function(d,n){d.css("left",n)},setTop:function(d,n){d.css("top",n)}},transform:{setPosition:function(d,n,k,v,s){d[0].style[m]="translate3d("+(n-k)+"px, "+(v-s)+"px, 0)"}}},m=function(){var d=/^(Moz|Webkit|Khtml|O|ms|Icab)(?=[A-Z])/,n=b("script")[0].style,k="",v;for(v in n)if(d.test(v)){k=v.match(d)[0];break}if("WebkitOpacity"in n)k="Webkit";if("KhtmlOpacity"in n)k="Khtml";return function(s){return k+(k.length>0?
s.charAt(0).toUpperCase()+s.slice(1):s)}}()("transform"),q=b("<div ></div>",{style:"background:#fff"}).css("background-position-x")!==e,x=q?function(d,n,k){d.css({"background-position-x":n,"background-position-y":k})}:function(d,n,k){d.css("background-position",n+" "+k)},H=q?function(d){return[d.css("background-position-x"),d.css("background-position-y")]}:function(d){return d.css("background-position").split(" ")},y=j.requestAnimationFrame||j.webkitRequestAnimationFrame||j.mozRequestAnimationFrame||j.oRequestAnimationFrame||
j.msRequestAnimationFrame||function(d){setTimeout(d,1E3/60)};a.prototype={init:function(){this.options.name=c+"_"+Math.floor(Math.random()*1E9);this._defineElements();this._defineGetters();this._defineSetters();this._handleWindowLoadAndResize();this._detectViewport();this.refresh({firstLoad:true});this.options.scrollProperty==="scroll"?this._handleScrollEvent():this._startAnimationLoop()},_defineElements:function(){if(this.element===l.body)this.element=j;this.$scrollElement=b(this.element);this.$element=
this.element===j?b("body"):this.$scrollElement;this.$viewportElement=this.options.viewportElement!==e?b(this.options.viewportElement):this.$scrollElement[0]===j||this.options.scrollProperty==="scroll"?this.$scrollElement:this.$scrollElement.parent()},_defineGetters:function(){var d=this,n=g[d.options.scrollProperty];this._getScrollLeft=function(){return n.getLeft(d.$scrollElement)};this._getScrollTop=function(){return n.getTop(d.$scrollElement)}},_defineSetters:function(){var d=this,n=g[d.options.scrollProperty],
k=h[d.options.positionProperty],v=n.setLeft,s=n.setTop;this._setScrollLeft=typeof v==="function"?function(z){v(d.$scrollElement,z)}:b.noop;this._setScrollTop=typeof s==="function"?function(z){s(d.$scrollElement,z)}:b.noop;this._setPosition=k.setPosition||function(z,K,J,C,M){d.options.horizontalScrolling&&k.setLeft(z,K,J);d.options.verticalScrolling&&k.setTop(z,C,M)}},_handleWindowLoadAndResize:function(){var d=this,n=b(j);d.options.responsive&&n.bind("load."+this.name,function(){d.refresh()});n.bind("resize."+
this.name,function(){d._detectViewport();d.options.responsive&&d.refresh()})},refresh:function(d){var n=this,k=n._getScrollLeft(),v=n._getScrollTop();if(!d||!d.firstLoad)this._reset();this._setScrollLeft(0);this._setScrollTop(0);this._setOffsets();this._findParticles();this._findBackgrounds();d&&d.firstLoad&&/WebKit/.test(navigator.userAgent)&&b(j).load(function(){var s=n._getScrollLeft(),z=n._getScrollTop();n._setScrollLeft(s+1);n._setScrollTop(z+1);n._setScrollLeft(s);n._setScrollTop(z)});this._setScrollLeft(k);
this._setScrollTop(v)},_detectViewport:function(){var d=this.$viewportElement.offset(),n=d!==null&&d!==e;this.viewportWidth=this.$viewportElement.width();this.viewportHeight=this.$viewportElement.height();this.viewportOffsetTop=n?d.top:0;this.viewportOffsetLeft=n?d.left:0},_findParticles:function(){var d=this;this._getScrollLeft();this._getScrollTop();if(this.particles!==e)for(var n=this.particles.length-1;n>=0;n--)this.particles[n].$element.data("stellar-elementIsActive",e);this.particles=[];this.options.parallaxElements&&
this.$element.find("[data-stellar-ratio]").each(function(){var k=b(this),v,s,z,K,J,C,M,I=0,T=0,Q=0,r=0;if(k.data("stellar-elementIsActive")){if(k.data("stellar-elementIsActive")!==this)return}else k.data("stellar-elementIsActive",this);d.options.showElement(k);if(k.data("stellar-startingLeft")){k.css("left",k.data("stellar-startingLeft"));k.css("top",k.data("stellar-startingTop"))}else{k.data("stellar-startingLeft",k.css("left"));k.data("stellar-startingTop",k.css("top"))}z=k.position().left;K=k.position().top;
J=k.css("margin-left")==="auto"?0:parseInt(k.css("margin-left"),10);v=k.css("margin-top")==="auto"?0:parseInt(k.css("margin-top"),10);J=k.offset().left-J;M=k.offset().top-v;k.parents().each(function(){var u=b(this);if(u.data("stellar-offset-parent")===true){I=Q;T=r;C=u;return false}else{Q+=u.position().left;r+=u.position().top}});v=k.data("stellar-horizontal-offset")!==e?k.data("stellar-horizontal-offset"):C!==e&&C.data("stellar-horizontal-offset")!==e?C.data("stellar-horizontal-offset"):d.horizontalOffset;
s=k.data("stellar-vertical-offset")!==e?k.data("stellar-vertical-offset"):C!==e&&C.data("stellar-vertical-offset")!==e?C.data("stellar-vertical-offset"):d.verticalOffset;d.particles.push({$element:k,$offsetParent:C,isFixed:k.css("position")==="fixed",horizontalOffset:v,verticalOffset:s,startingPositionLeft:z,startingPositionTop:K,startingOffsetLeft:J,startingOffsetTop:M,parentOffsetLeft:I,parentOffsetTop:T,stellarRatio:k.data("stellar-ratio")!==e?k.data("stellar-ratio"):1,width:k.outerWidth(true),
height:k.outerHeight(true),isHidden:false})})},_findBackgrounds:function(){var d=this,n=this._getScrollLeft(),k=this._getScrollTop(),v;this.backgrounds=[];if(this.options.parallaxBackgrounds){v=this.$element.find("[data-stellar-background-ratio]");if(this.$element.data("stellar-background-ratio"))v=v.add(this.$element);v.each(function(){var s=b(this),z=H(s),K,J,C,M,I,T=0,Q=0,r=0,u=0;if(s.data("stellar-backgroundIsActive")){if(s.data("stellar-backgroundIsActive")!==this)return}else s.data("stellar-backgroundIsActive",
this);if(s.data("stellar-backgroundStartingLeft"))x(s,s.data("stellar-backgroundStartingLeft"),s.data("stellar-backgroundStartingTop"));else{s.data("stellar-backgroundStartingLeft",z[0]);s.data("stellar-backgroundStartingTop",z[1])}C=s.css("margin-left")==="auto"?0:parseInt(s.css("margin-left"),10);K=s.css("margin-top")==="auto"?0:parseInt(s.css("margin-top"),10);C=s.offset().left-C-n;M=s.offset().top-K-k;s.parents().each(function(){var B=b(this);if(B.data("stellar-offset-parent")===true){T=r;Q=u;
I=B;return false}else{r+=B.position().left;u+=B.position().top}});K=s.data("stellar-horizontal-offset")!==e?s.data("stellar-horizontal-offset"):I!==e&&I.data("stellar-horizontal-offset")!==e?I.data("stellar-horizontal-offset"):d.horizontalOffset;J=s.data("stellar-vertical-offset")!==e?s.data("stellar-vertical-offset"):I!==e&&I.data("stellar-vertical-offset")!==e?I.data("stellar-vertical-offset"):d.verticalOffset;d.backgrounds.push({$element:s,$offsetParent:I,isFixed:s.css("background-attachment")===
"fixed",horizontalOffset:K,verticalOffset:J,startingValueLeft:z[0],startingValueTop:z[1],startingBackgroundPositionLeft:isNaN(parseInt(z[0],10))||-1!==z[0].indexOf("%")?0:parseInt(z[0],10),startingBackgroundPositionTop:isNaN(parseInt(z[1],10))||-1!==z[1].indexOf("%")?0:parseInt(z[1],10),startingPositionLeft:s.position().left,startingPositionTop:s.position().top,startingOffsetLeft:C,startingOffsetTop:M,parentOffsetLeft:T,parentOffsetTop:Q,stellarRatio:s.data("stellar-background-ratio")===e?1:s.data("stellar-background-ratio")})})}},
_reset:function(){var d,n,k,v;for(v=this.particles.length-1;v>=0;v--){d=this.particles[v];n=d.$element.data("stellar-startingLeft");k=d.$element.data("stellar-startingTop");this._setPosition(d.$element,n,n,k,k);this.options.showElement(d.$element);d.$element.data("stellar-startingLeft",null).data("stellar-elementIsActive",null).data("stellar-backgroundIsActive",null)}for(v=this.backgrounds.length-1;v>=0;v--){d=this.backgrounds[v];d.$element.data("stellar-backgroundStartingLeft",null).data("stellar-backgroundStartingTop",
null);x(d.$element,d.startingValueLeft,d.startingValueTop)}},destroy:function(){this._reset();this.$scrollElement.unbind("resize."+this.name).unbind("scroll."+this.name);this._animationLoop=b.noop;b(j).unbind("load."+this.name).unbind("resize."+this.name)},_setOffsets:function(){var d=this,n=b(j);n.unbind("resize.horizontal-"+this.name).unbind("resize.vertical-"+this.name);if(typeof this.options.horizontalOffset==="function"){this.horizontalOffset=this.options.horizontalOffset();n.bind("resize.horizontal-"+
this.name,function(){d.horizontalOffset=d.options.horizontalOffset()})}else this.horizontalOffset=this.options.horizontalOffset;if(typeof this.options.verticalOffset==="function"){this.verticalOffset=this.options.verticalOffset();n.bind("resize.vertical-"+this.name,function(){d.verticalOffset=d.options.verticalOffset()})}else this.verticalOffset=this.options.verticalOffset},_repositionElements:function(){var d=this._getScrollLeft(),n=this._getScrollTop(),k,v,s,z=s=true,K,J,C,M;if(!(this.currentScrollLeft===
d&&this.currentScrollTop===n&&this.currentWidth===this.viewportWidth&&this.currentHeight===this.viewportHeight)){this.currentScrollLeft=d;this.currentScrollTop=n;this.currentWidth=this.viewportWidth;this.currentHeight=this.viewportHeight;for(M=this.particles.length-1;M>=0;M--){k=this.particles[M];v=k.isFixed?1:0;if(this.options.horizontalScrolling){K=(d+k.horizontalOffset+this.viewportOffsetLeft+k.startingPositionLeft-k.startingOffsetLeft+k.parentOffsetLeft)*-(k.stellarRatio+v-1)+k.startingPositionLeft;
J=K-k.startingPositionLeft+k.startingOffsetLeft}else{K=k.startingPositionLeft;J=k.startingOffsetLeft}if(this.options.verticalScrolling){v=(n+k.verticalOffset+this.viewportOffsetTop+k.startingPositionTop-k.startingOffsetTop+k.parentOffsetTop)*-(k.stellarRatio+v-1)+k.startingPositionTop;C=v-k.startingPositionTop+k.startingOffsetTop}else{v=k.startingPositionTop;C=k.startingOffsetTop}if(this.options.hideDistantElements){z=!this.options.horizontalScrolling||J+k.width>(k.isFixed?0:d)&&J<(k.isFixed?0:d)+
this.viewportWidth+this.viewportOffsetLeft;s=!this.options.verticalScrolling||C+k.height>(k.isFixed?0:n)&&C<(k.isFixed?0:n)+this.viewportHeight+this.viewportOffsetTop}if(z&&s){if(k.isHidden){this.options.showElement(k.$element);k.isHidden=false}this._setPosition(k.$element,K,k.startingPositionLeft,v,k.startingPositionTop)}else if(!k.isHidden){this.options.hideElement(k.$element);k.isHidden=true}}for(M=this.backgrounds.length-1;M>=0;M--){k=this.backgrounds[M];v=k.isFixed?0:1;s=this.options.horizontalScrolling?
(d+k.horizontalOffset-this.viewportOffsetLeft-k.startingOffsetLeft+k.parentOffsetLeft-k.startingBackgroundPositionLeft)*(v-k.stellarRatio)+"px":k.startingValueLeft;v=this.options.verticalScrolling?(n+k.verticalOffset-this.viewportOffsetTop-k.startingOffsetTop+k.parentOffsetTop-k.startingBackgroundPositionTop)*(v-k.stellarRatio)+"px":k.startingValueTop;x(k.$element,s,v)}}},_handleScrollEvent:function(){var d=this,n=false,k=function(){d._repositionElements();n=false},v=function(){if(!n){y(k);n=true}};
b(j).bind("load."+d.name,function(){d.$scrollElement.bind("scroll."+d.name,v);v()})},_startAnimationLoop:function(){var d=this;this._animationLoop=function(){y(d._animationLoop);d._repositionElements()};this._animationLoop()}};b.fn[c]=function(d){var n=arguments;if(d===e||typeof d==="object")return this.each(function(){b.data(this,"plugin_"+c)||b.data(this,"plugin_"+c,new a(this,d))});else if(typeof d==="string"&&d[0]!=="_"&&d!=="init")return this.each(function(){var k=b.data(this,"plugin_"+c);k instanceof
a&&typeof k[d]==="function"&&k[d].apply(k,Array.prototype.slice.call(n,1));d==="destroy"&&b.data(this,"plugin_"+c,null)})};b[c]=function(){var d=b(j);return d.stellar.apply(d,Array.prototype.slice.call(arguments,0))};b[c].scrollProperty=g;b[c].positionProperty=h;j.Stellar=a})(jQuery,this,document);
(function(b,j,l){b.fn.responsiveSlides=function(e){var a=b.extend({auto:true,speed:500,timeout:4E3,pager:false,nav:false,random:false,pause:false,pauseControls:true,prevText:"Previous",nextText:"Next",maxwidth:"",navContainer:"",manualControls:"",namespace:"rslides",before:b.noop,after:b.noop},e);return this.each(function(){l++;var c=b(this),f,g,h,m,q,x,H=0,y=c.children(),d=y.size(),n=parseFloat(a.speed),k=parseFloat(a.timeout),v=parseFloat(a.maxwidth),s=a.namespace,z=s+l,K=s+"_nav "+z+"_nav",J=s+
"_here",C=z+"_on",M=z+"_s",I=b("<ul class='"+s+"_tabs "+z+"_tabs' ></ul>"),T={"float":"left",position:"relative",opacity:1,zIndex:2},Q={"float":"none",position:"absolute",opacity:0,zIndex:1},r=function(){var E=(document.body||document.documentElement).style,R="transition";if("string"===typeof E[R])return true;f=["Moz","Webkit","Khtml","O","ms"];R=R.charAt(0).toUpperCase()+R.substr(1);var V;for(V=0;V<f.length;V++)if("string"===typeof E[f[V]+R])return true;return false}(),u=function(E){a.before(E);r?(y.removeClass(C).css(Q).eq(E).addClass(C).css(T),
H=E,setTimeout(function(){a.after(E)},n)):y.stop().fadeOut(n,function(){b(this).removeClass(C).css(Q).css("opacity",1)}).eq(E).fadeIn(n,function(){b(this).addClass(C).css(T);a.after(E);H=E})};a.random&&(y.sort(function(){return Math.round(Math.random())-0.5}),c.empty().append(y));y.each(function(E){this.id=M+E});c.addClass(s+" "+z);e&&e.maxwidth&&c.css("max-width",v);y.hide().css(Q).eq(0).addClass(C).css(T).show();r&&y.show().css({"-webkit-transition":"opacity "+n+"ms ease-in-out","-moz-transition":"opacity "+
n+"ms ease-in-out","-o-transition":"opacity "+n+"ms ease-in-out",transition:"opacity "+n+"ms ease-in-out"});if(1<y.size()){if(k<n+100)return;if(a.pager&&!a.manualControls){var B=[];y.each(function(E){E+=1;B+="<li><a href='#' class='"+M+E+"'>"+E+"</a></li>"});I.append(B);e.navContainer?b(a.navContainer).append(I):c.after(I)}a.manualControls&&(I=b(a.manualControls),I.addClass(s+"_tabs "+z+"_tabs"));(a.pager||a.manualControls)&&I.find("li").each(function(E){b(this).addClass(M+(E+1))});if(a.pager||a.manualControls){x=
I.find("a");g=function(E){x.closest("li").removeClass(J).eq(E).addClass(J)}}a.auto&&(h=function(){q=setInterval(function(){y.stop(true,true);var E=H+1<d?H+1:0;(a.pager||a.manualControls)&&g(E);u(E)},k)},h());m=function(){a.auto&&(clearInterval(q),h())};a.pause&&c.hover(function(){clearInterval(q)},function(){m()});if(a.pager||a.manualControls){x.bind("click",function(E){E.preventDefault();a.pauseControls||m();E=x.index(this);H===E||b("."+C).queue("fx").length||(g(E),u(E))}).eq(0).closest("li").addClass(J);
a.pauseControls&&x.hover(function(){clearInterval(q)},function(){m()})}if(a.nav){s="<a href='#' class='"+K+" prev'>"+a.prevText+"</a><a href='#' class='"+K+" next'>"+a.nextText+"</a>";e.navContainer?b(a.navContainer).append(s):c.after(s);z=b("."+z+"_nav");var G=z.filter(".prev");z.bind("click",function(E){E.preventDefault();E=b("."+C);if(!E.queue("fx").length){var R=y.index(E);E=R-1;R=R+1<d?H+1:0;u(b(this)[0]===G[0]?E:R);if(a.pager||a.manualControls)g(b(this)[0]===G[0]?E:R);a.pauseControls||m()}});
a.pauseControls&&z.hover(function(){clearInterval(q)},function(){m()})}}if("undefined"===typeof document.body.style.maxWidth&&e.maxwidth){var F=function(){c.css("width","100%");c.width()>v&&c.css("width",v)};F();b(j).bind("resize",function(){F()})}})}})(jQuery,this,0);
(function(b,j,l){function e(i,o){return i.res-o.res}function a(i,o){var t,p,A;if(i&&o){A=d.parseSet(o);i=d.makeUrl(i);for(t=0;t<A.length;t++)if(i==d.makeUrl(A[t].url)){p=A[t];break}}return p}j.createElement("picture");var c,f,g,h,m,q,x,H,y,d={},n=function(){},k=j.createElement("img"),v=k.getAttribute,s=k.setAttribute,z=k.removeAttribute,K=j.documentElement,J={},C={xQuant:1,lazyFactor:0.4,maxX:2},M="webkitBackfaceVisibility"in K.style,I=navigator.userAgent,T=/AppleWebKit/i.test(I),Q=/rident/.test(I)||
/ecko/.test(I)&&I.match(/rv\:(\d+)/)&&RegExp.$1>35,r=0,u="currentSrc",B=/\s+\+?\d+(e\d+)?w/,G=/(\([^)]+\))?\s*(.+)/,F=/^([\+eE\d\.]+)(w|x)$/,E=/\s*\d+h\s*/;I=b.respimgCFG;var R=true,V={},Z={},aa=b.devicePixelRatio,N={px:1,"in":96},Y=j.createElement("a"),W=false,ba=function(i,o,t,p){i.addEventListener?i.addEventListener(o,t,p||false):i.attachEvent&&i.attachEvent("on"+o,t)},U=function(i,o,t,p){i.removeEventListener?i.removeEventListener(o,t,p||false):i.detachEvent&&i.detachEvent("on"+o,t)},fa=function(i){var o=
{};return function(t){return t in o||(o[t]=i(t)),o[t]}},ha=function(){var i=/^([\d\.]+)(em|vw|px)$/,o=function(){for(var p=arguments,A=0,D=p[0];++A in p;)D=D.replace(p[A],p[++A]);return D},t=fa(function(p){return"return "+o((p||"").toLowerCase(),/\band\b/g,"&&",/,/g,"||",/min-([a-z-\s]+):/g,"e.$1>=",/max-([a-z-\s]+):/g,"e.$1<=",/calc([^)]+)/g,"($1)",/(\d+[\.]*[\d]*)([a-z]+)/g,"($1 * e.$2)",/^(?!(e.[a-z]|[0-9\.&=|><\+\-\*\(\)\/])).*/gi,"")});return function(p,A){var D;if(!(p in V))if(V[p]=false,A&&
(D=p.match(i)))V[p]=D[1]*N[D[2]];else try{V[p]=(new Function("e",t(p)))(N)}catch(O){}return V[p]}}(),ga=function(i,o){return i.w?(i.cWidth=d.calcListLength(o||"100vw"),i.res=i.w/i.cWidth):i.res=i.x,i},da=function(i){var o,t,p=i||{};if(p.elements&&1==p.elements.nodeType&&("IMG"==p.elements.nodeName.toUpperCase()?p.elements=[p.elements]:(p.context=p.elements,p.elements=null)),o=p.elements||d.qsa(p.context||j,p.reevaluate||p.reparse?d.sel:d.selShort),t=o.length){d.setupRun(p);W=true;for(i=0;t>i;i++){r++;
6>r&&!o[i].complete&&r++;d.fillImg(o[i],p)}d.teardownRun(p);r++}},ma=function(){var i=function(){U(this,"load",i);U(this,"error",i);d.fillImgs({elements:[this]})};return function(o){U(o,"load",i);U(o,"error",i);ba(o,"error",i);ba(o,"load",i)}}(),na=fa(function(i){var o=[1,"x"];i=(i||"").trim?(i||"").trim():(i||"").replace(/^\s+|\s+$/g,"");return i&&(i=i.replace(E,""),o=i.match(F)?[1*RegExp.$1,RegExp.$2]:false),o});u in k||(u="src");J["image/jpeg"]=true;J["image/gif"]=true;J["image/png"]=true;J["image/svg+xml"]=
j.implementation.hasFeature("http://wwwindow.w3.org/TR/SVG11/feature#Image","1.1");d.ns=("ri"+(new Date).getTime()).substr(0,9);d.supSrcset="srcset"in k;d.supSizes="sizes"in k;d.selShort="picture>img,img[srcset]";d.sel=d.selShort;d.cfg=C;d.supSrcset&&(d.sel+=",img[data-risrcset]");d.DPR=aa||1;d.u=N;d.types=J;H=d.supSrcset&&!d.supSizes;d.setSize=n;d.makeUrl=fa(function(i){return Y.href=i,Y.href});d.qsa=function(i,o){return i.querySelectorAll(o)};d.matchesMedia=function(){return d.matchesMedia=b.matchMedia&&
(matchMedia("(min-width: 0.1em)")||{}).matches?function(i){return!i||matchMedia(i).matches}:d.mMQ,d.matchesMedia.apply(this,arguments)};d.mMQ=function(i){return i?ha(i):true};d.calcLength=function(i){i=ha(i,true)||false;return 0>i&&(i=false),i};d.supportsType=function(i){return i?J[i]:true};d.parseSize=fa(function(i){i=(i||"").match(G);return{media:i&&i[1],length:i&&i[2]}});d.parseSet=function(i){if(!i.cands){var o,t,p,A,D,O,L=i.srcset;for(i.cands=[];L;){L=L.replace(/^\s+/g,"");o=L.search(/\s/g);
p=null;-1!=o?(t=L.slice(0,o),A=t.charAt(t.length-1),","!=A&&t||(t=t.replace(/,+$/,""),p=""),L=L.slice(o+1),null==p&&(D=L.indexOf(","),-1!=D?(p=L.slice(0,D),L=L.slice(D+1)):(p=L,L=""))):(t=L,L="");t&&(p=na(p))&&(O={url:t.replace(/^,+/,""),set:i},O[p[1]]=p[0],"x"==p[1]&&1==p[0]&&(i.has1x=true),i.cands.push(O))}}return i.cands};d.getEmValue=function(){var i;if(!x&&(i=j.body)){var o=j.createElement("div"),t=K.style.cssText,p=i.style.cssText;o.style.cssText="position:absolute;left:0;visibility:hidden;display:block;padding:0;border:none;font-size:1em;width:1em;overflow:hidden;clip:rect(0px, 0px, 0px, 0px)";
K.style.cssText="font-size:100%!important;";i.style.cssText="font-size:100%!important;";i.appendChild(o);x=o.offsetWidth;i.removeChild(o);x=parseFloat(x,10);K.style.cssText=t;i.style.cssText=p}return x||16};d.calcListLength=function(i){if(!(i in Z)||C.uT){var o,t,p,A,D,O,L=(i.trim?i.trim():i.replace(/^\s+|\s+$/g,"")).split(/\s*,\s*/),w=false;D=0;for(O=L.length;O>D&&(o=L[D],t=d.parseSize(o),p=t.length,A=t.media,!p||!d.matchesMedia(A)||(w=d.calcLength(p))===false);D++);Z[i]=w?w:N.width}return Z[i]};
d.setRes=function(i){var o;if(i){o=d.parseSet(i);for(var t=0,p=o.length;p>t;t++)ga(o[t],i.sizes)}return o};d.setRes.res=ga;d.applySetCandidate=function(i,o){if(i.length){var t,p,A,D,O,L,w,S,X,$,P,ea=o[d.ns],ia=true;S=h;var ja=q;L=ea.curSrc||o[u];if(!(p=ea.curCan)){w=L;P=i[0].set;var ca;p=(!P&&w&&(P=o[d.ns].sets,P=P&&P[P.length-1]),ca=a(w,P),ca&&(w=d.makeUrl(w),o[d.ns].curSrc=w,o[d.ns].curCan=ca,ca.res||ga(ca,ca.set.sizes)),ca)}w=p;p=d.DPR;P=w&&w.res;if(!D)if(L){$=Q&&!o.complete&&w&&P>p;if(!$)if(!(w&&
!(m>P))){w&&p>P&&P>c&&(f>P&&(S*=0.87,ja+=0.04*p),w.res+=S*Math.pow(P-ja,2));S=!ea.pic||w&&w.set==i[0].set;if(w&&S&&w.res>=p)D=w;else if(!T)if(!o.complete)if(v.call(o,"src"))if(!o.lazyload)if(!(Q&&!(4>r))){if(S=!S)if(o.getBoundingClientRect){var ka,la;S=o.getBoundingClientRect();S=!!((A=S.bottom)>=-9&&(la=S.top)<=N.height+9&&(O=S.right)>=-9&&(ka=S.left)<=N.height+9&&(A||O||ka||la))}else S=true;S||(D=w,X=L,ia="L",ma(o))}}}if(!D){P&&(w.res-=(w.res-P)/2);i.sort(e);O=i.length;D=i[O-1];for(A=0;O>A;A++)if(t=
i[A],t.res>=p){D=A-1;if(A=i[D]){if(O=A=t.res-p){if($=$||L!=d.makeUrl(t.url)){O=i[D].res;A*=Math.pow(O,2);$=(g||(A/=1.3),O+=A,O>p)}O=$}A=O}D=A?i[D]:t;break}}return P&&(w.res=P),D&&(X=d.makeUrl(D.url),ea.curSrc=X,ea.curCan=D,X!=L&&d.setSrc(o,D),d.setSize(o)),ia}};d.setSrc=function(i,o){var t;i.src=o.url;M&&(t=i.style.zoom,i.style.zoom="0.999",i.style.zoom=t)};d.getSet=function(i){var o,t,p=false,A=i[d.ns].sets;for(i=0;i<A.length&&!p;i++)if(o=A[i],o.srcset&&d.matchesMedia(o.media)&&(t=d.supportsType(o.type))){"pending"==
t&&(o=t);p=o;break}return p};d.parseSets=function(i,o,t){var p,A,D,O,L="PICTURE"==o.nodeName.toUpperCase(),w=i[d.ns];(w.src===l||t.src)&&(w.src=v.call(i,"src"),w.src?s.call(i,"data-risrc",w.src):z.call(i,"data-risrc"));(w.srcset===l||!d.supSrcset||i.srcset||t.srcset)&&(p=v.call(i,"srcset"),w.srcset=p,O=true);w.sets=[];if(L){w.pic=true;t=w.sets;var S,X,$,P=o.getElementsByTagName("source");o=0;for(S=P.length;S>o;o++){X=P[o];X[d.ns]=true;($=X.getAttribute("srcset"))&&t.push({srcset:$,media:X.getAttribute("media"),
type:X.getAttribute("type"),sizes:X.getAttribute("sizes")})}}w.srcset?(A={srcset:w.srcset,sizes:v.call(i,"sizes")},w.sets.push(A),D=(H||w.src)&&B.test(w.srcset||""),D||!w.src||a(w.src,A)||A.has1x||(A.srcset+=", "+w.src,A.cands.push({url:w.src,x:1,set:A}))):w.src&&w.sets.push({srcset:w.src,sizes:null});w.curCan=null;w.curSrc=l;w.supported=!(L||A&&!d.supSrcset||D);O&&d.supSrcset&&!w.supported&&(p?(s.call(i,"data-risrcset",p),i.srcset=""):z.call(i,"data-risrcset"));w.supported&&!w.srcset&&(!w.src&&i.src||
i.src!=d.makeUrl(w.src))&&(null==w.src?i.removeAttribute("src"):i.src=w.src);w.parsed=true};d.fillImg=function(i,o){var t,p,A=o.reparse||o.reevaluate;if(i[d.ns]||(i[d.ns]={}),p=i[d.ns],"L"==p.evaled&&i.complete&&(p.evaled=false),A||!p.evaled){if(!p.parsed||o.reparse){if(t=i.parentNode,!t)return;d.parseSets(i,t,o)}if(p.supported)p.evaled=true;else{var D;t=d.getSet(i);p=false;"pending"!=t&&(p=true,t&&(D=d.setRes(t),p=d.applySetCandidate(D,i)));i[d.ns].evaled=p}}};d.setupRun=function(i){if(!W||i.reevaluate||
R){var o;R=false;aa=b.devicePixelRatio;V={};Z={};o=(aa||1)*C.xQuant;C.uT||(C.maxX=Math.max(1.3,C.maxX),o=Math.min(o,C.maxX),d.DPR=o);N.width=Math.max(b.innerWidth||0,K.clientWidth);N.height=Math.max(b.innerHeight||0,K.clientHeight);N.vw=N.width/100;N.vh=N.height/100;N.em=d.getEmValue();N.rem=N.em;h=C.lazyFactor/2;h=h*o+h;q=0.1*o;c=0.5+0.2*o;f=0.5+0.25*o;m=o+1.3;(g=N.width>N.height)||(h*=0.9);Q&&(h*=0.9);i.elements||i.context||clearTimeout(y)}};b.HTMLPictureElement?(da=n,d.fillImg=n):function(){var i,
o=b.attachEvent?/d$|^c/:/d$|^c|^i/,t=function(){var D=j.readyState||"";A=setTimeout(t,"loading"==D?200:999);j.body&&(i=i||o.test(D),d.fillImgs(),i&&(r+=6,clearTimeout(A)))},p=function(){d.fillImgs({reevaluate:true})},A=setTimeout(t,j.body?9:99);ba(b,"resize",function(){clearTimeout(y);R=true;y=setTimeout(p,99)});ba(j,"readystatechange",t)}();d.respimage=da;d.fillImgs=da;d.teardownRun=n;da._=d;b.respimage=da;for(b.respimgCFG={ri:d,push:function(i){var o=i.shift();"function"==typeof d[o]?d[o].apply(d,
i):(C[o]=i[0],W&&d.fillImgs({reevaluate:true}))}};I&&I.length;)b.respimgCFG.push(I.shift())})(window,document);
(function(){function b(){if(document.body){var r=document.body,u=document.documentElement,B=window.innerHeight,G=r.scrollHeight;n=document.compatMode.indexOf("CSS")>=0?u:r;k=r;q.keyboardSupport&&window.addEventListener("keydown",e,false);d=true;if(top!=self)H=true;else if(G>B&&(r.offsetHeight<=B||u.offsetHeight<=B)){var F=false;u.style.height="auto";setTimeout(function(){if(!F&&u.scrollHeight!=document.height){F=true;setTimeout(function(){u.style.height=document.height+"px";F=false},500)}},10);if(n.offsetHeight<=
B){B=document.createElement("div");B.style.clear="both";r.appendChild(B)}}if(!q.fixedBackground&&!x){r.style.backgroundAttachment="scroll";u.style.backgroundAttachment="scroll"}}}function j(r,u,B,G){G||(G=1E3);g(u,B);if(q.accelerationMax!=1){var F=+new Date-J;if(F<q.accelerationDelta){F=(1+30/F)/2;if(F>1){F=Math.min(F,q.accelerationMax);u*=F;B*=F}}J=+new Date}z.push({x:u,y:B,lastX:u<0?0.99:-0.99,lastY:B<0?0.99:-0.99,start:+new Date});if(!K){var E=r===document.body,R=function(){for(var V=+new Date,
Z=0,aa=0,N=0;N<z.length;N++){var Y=z[N],W=V-Y.start,ba=W>=q.animationTime,U=ba?1:W/q.animationTime;if(q.pulseAlgorithm){W=U;if(W>=1)U=1;else if(W<=0)U=0;else{if(q.pulseNormalize==1)q.pulseNormalize/=h(1);U=h(W)}}W=Y.x*U-Y.lastX>>0;U=Y.y*U-Y.lastY>>0;Z+=W;aa+=U;Y.lastX+=W;Y.lastY+=U;if(ba){z.splice(N,1);N--}}if(E)window.scrollBy(Z,aa);else{if(Z)r.scrollLeft+=Z;if(aa)r.scrollTop+=aa}if(!u&&!B)z=[];if(z.length)T(R,r,G/q.frameRate+1);else K=false};T(R,r,0);K=true}}function l(r){d||b();var u=r.target,
B=f(u);if(!B||r.defaultPrevented||(k.nodeName||"").toLowerCase()==="embed".toLowerCase()||(u.nodeName||"").toLowerCase()==="embed".toLowerCase()&&/\.pdf/i.test(u.src))return true;u=r.wheelDeltaX||0;var G=r.wheelDeltaY||0;if(!u&&!G)G=r.wheelDelta||0;var F;if(F=!q.touchpadSupport)if(F=G){F=Math.abs(F);v.push(F);v.shift();clearTimeout(I);F=!(Math.floor(v[0]/120)==v[0]/120&&Math.floor(v[1]/120)==v[1]/120&&Math.floor(v[2]/120)==v[2]/120)}else F=void 0;if(F)return true;if(Math.abs(u)>1.2)u*=q.stepSize/
120;if(Math.abs(G)>1.2)G*=q.stepSize/120;j(B,-u,-G);r.preventDefault()}function e(r){var u=r.target,B=r.ctrlKey||r.altKey||r.metaKey||r.shiftKey&&r.keyCode!==s.spacebar;if(/input|textarea|select|embed/i.test(u.nodeName)||u.isContentEditable||r.defaultPrevented||B)return true;if((u.nodeName||"").toLowerCase()==="button".toLowerCase()&&r.keyCode===s.spacebar)return true;var G;G=u=0;B=f(k);var F=B.clientHeight;if(B==document.body)F=window.innerHeight;switch(r.keyCode){case s.up:G=-q.arrowScroll;break;
case s.down:G=q.arrowScroll;break;case s.spacebar:G=r.shiftKey?1:-1;G=-G*F*0.9;break;case s.pageup:G=-F*0.9;break;case s.pagedown:G=F*0.9;break;case s.home:G=-B.scrollTop;break;case s.end:F=B.scrollHeight-B.scrollTop-F;G=F>0?F+10:0;break;case s.left:u=-q.arrowScroll;break;case s.right:u=q.arrowScroll;break;default:return true}j(B,u,G);r.preventDefault()}function a(r){k=r.target}function c(r,u){for(var B=r.length;B--;)C[M(r[B])]=u;return u}function f(r){var u=[],B=n.scrollHeight;do{var G=C[M(r)];if(G)return c(u,
G);u.push(r);if(B===r.scrollHeight){if(!H||n.clientHeight+10<B)return c(u,document.body)}else if(r.clientHeight+10<r.scrollHeight){overflow=getComputedStyle(r,"").getPropertyValue("overflow-y");if(overflow==="scroll"||overflow==="auto")return c(u,r)}}while(r=r.parentNode)}function g(r,u){r=r>0?1:-1;u=u>0?1:-1;if(y.x!==r||y.y!==u){y.x=r;y.y=u;z=[];J=0}}function h(r){var u;r*=q.pulseScale;if(r<1)u=r-(1-Math.exp(-r));else{u=Math.exp(-1);r-=1;r=1-Math.exp(-r);u+=r*(1-u)}return u*q.pulseNormalize}var m=
{frameRate:150,animationTime:400,stepSize:120,pulseAlgorithm:true,pulseScale:8,pulseNormalize:1,accelerationDelta:20,accelerationMax:1,keyboardSupport:true,arrowScroll:50,touchpadSupport:true,fixedBackground:true,excluded:""},q=m,x=false,H=false,y={x:0,y:0},d=false,n=document.documentElement,k,v=[120,120,120],s={left:37,up:38,right:39,down:40,spacebar:32,pageup:33,pagedown:34,end:35,home:36};q=m;var z=[],K=false,J=+new Date,C={};setInterval(function(){C={}},1E4);var M=function(){var r=0;return function(u){return u.uniqueID||
(u.uniqueID=r++)}}(),I,T=function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||function(r,u,B){window.setTimeout(r,B||1E3/60)}}();m=/chrome/i.test(window.navigator.userAgent);var Q=null;if("onwheel"in document.createElement("div"))Q="wheel";else if("onmousewheel"in document.createElement("div"))Q="mousewheel";if(Q&&m){window.addEventListener(Q,l,false);window.addEventListener("mousedown",a,false);window.addEventListener("load",b,false)}})();
if("undefined"==typeof jQuery)throw Error("Bootstrap's JavaScript requires jQuery");(function(b){b=b.fn.jquery.split(" ")[0].split(".");if(b[0]<2&&b[1]<9||1==b[0]&&9==b[1]&&b[2]<1)throw Error("Bootstrap's JavaScript requires jQuery version 1.9.1 or higher");})(jQuery);
(function(b){var j=function(e){b(e).on("click",'[data-dismiss="alert"]',this.close)};j.VERSION="3.3.2";j.TRANSITION_DURATION=150;j.prototype.close=function(e){function a(){g.detach().trigger("closed.bs.alert").remove()}var c=b(this),f=c.attr("data-target");f||(f=c.attr("href"),f=f&&f.replace(/.*(?=#[^\s]*$)/,""));var g=b(f);e&&e.preventDefault();g.length||(g=c.closest(".alert"));g.trigger(e=b.Event("close.bs.alert"));e.isDefaultPrevented()||(g.removeClass("in"),b.support.transition&&g.hasClass("fade")?
g.one("bsTransitionEnd",a).emulateTransitionEnd(j.TRANSITION_DURATION):a())};var l=b.fn.alert;b.fn.alert=function(e){return this.each(function(){var a=b(this),c=a.data("bs.alert");c||a.data("bs.alert",c=new j(this));"string"==typeof e&&c[e].call(a)})};b.fn.alert.Constructor=j;b.fn.alert.noConflict=function(){return b.fn.alert=l,this};b(document).on("click.bs.alert.data-api",'[data-dismiss="alert"]',j.prototype.close)})(jQuery);
(function(b){function j(a){return this.each(function(){var c=b(this),f=c.data("bs.button"),g="object"==typeof a&&a;f||c.data("bs.button",f=new l(this,g));"toggle"==a?f.toggle():a&&f.setState(a)})}var l=function(a,c){this.$element=b(a);this.options=b.extend({},l.DEFAULTS,c);this.isLoading=false};l.VERSION="3.3.2";l.DEFAULTS={loadingText:"loading..."};l.prototype.setState=function(a){var c=this.$element,f=c.is("input")?"val":"html",g=c.data();a+="Text";null==g.resetText&&c.data("resetText",c[f]());
setTimeout(b.proxy(function(){c[f](null==g[a]?this.options[a]:g[a]);"loadingText"==a?(this.isLoading=true,c.addClass("disabled").attr("disabled","disabled")):this.isLoading&&(this.isLoading=false,c.removeClass("disabled").removeAttr("disabled"))},this),0)};l.prototype.toggle=function(){var a=true,c=this.$element.closest('[data-toggle="buttons"]');if(c.length){var f=this.$element.find("input");"radio"==f.prop("type")&&(f.prop("checked")&&this.$element.hasClass("active")?a=false:c.find(".active").removeClass("active"));
a&&f.prop("checked",!this.$element.hasClass("active")).trigger("change")}else this.$element.attr("aria-pressed",!this.$element.hasClass("active"));a&&this.$element.toggleClass("active")};var e=b.fn.button;b.fn.button=j;b.fn.button.Constructor=l;b.fn.button.noConflict=function(){return b.fn.button=e,this};b(document).on("click.bs.button.data-api",'[data-toggle^="button"]',function(a){var c=b(a.target);c.hasClass("btn")||(c=c.closest(".btn"));j.call(c,"toggle");a.preventDefault()}).on("focus.bs.button.data-api blur.bs.button.data-api",
'[data-toggle^="button"]',function(a){b(a.target).closest(".btn").toggleClass("focus",/^focus(in)?$/.test(a.type))})})(jQuery);
(function(b){function j(c){return this.each(function(){var f=b(this),g=f.data("bs.carousel"),h=b.extend({},l.DEFAULTS,f.data(),"object"==typeof c&&c),m="string"==typeof c?c:h.slide;g||f.data("bs.carousel",g=new l(this,h));"number"==typeof c?g.to(c):m?g[m]():h.interval&&g.pause().cycle()})}var l=function(c,f){this.$element=b(c);this.$indicators=this.$element.find(".carousel-indicators");this.options=f;this.$items=this.$active=this.interval=this.sliding=this.paused=null;this.options.keyboard&&this.$element.on("keydown.bs.carousel",
b.proxy(this.keydown,this));"hover"==this.options.pause&&!("ontouchstart"in document.documentElement)&&this.$element.on("mouseenter.bs.carousel",b.proxy(this.pause,this)).on("mouseleave.bs.carousel",b.proxy(this.cycle,this))};l.VERSION="3.3.2";l.TRANSITION_DURATION=600;l.DEFAULTS={interval:5E3,pause:"hover",wrap:true,keyboard:true};l.prototype.keydown=function(c){if(!/input|textarea/i.test(c.target.tagName)){switch(c.which){case 37:this.prev();break;case 39:this.next();break;default:return}c.preventDefault()}};
l.prototype.cycle=function(c){return c||(this.paused=false),this.interval&&clearInterval(this.interval),this.options.interval&&!this.paused&&(this.interval=setInterval(b.proxy(this.next,this),this.options.interval)),this};l.prototype.getItemIndex=function(c){return this.$items=c.parent().children(".item"),this.$items.index(c||this.$active)};l.prototype.getItemForDirection=function(c,f){var g=this.getItemIndex(f);if(("prev"==c&&0===g||"next"==c&&g==this.$items.length-1)&&!this.options.wrap)return f;
return this.$items.eq((g+("prev"==c?-1:1))%this.$items.length)};l.prototype.to=function(c){var f=this,g=this.getItemIndex(this.$active=this.$element.find(".item.active"));return c>this.$items.length-1||0>c?void 0:this.sliding?this.$element.one("slid.bs.carousel",function(){f.to(c)}):g==c?this.pause().cycle():this.slide(c>g?"next":"prev",this.$items.eq(c))};l.prototype.pause=function(c){return c||(this.paused=true),this.$element.find(".next, .prev").length&&b.support.transition&&(this.$element.trigger(b.support.transition.end),
this.cycle(true)),this.interval=clearInterval(this.interval),this};l.prototype.next=function(){return this.sliding?void 0:this.slide("next")};l.prototype.prev=function(){return this.sliding?void 0:this.slide("prev")};l.prototype.slide=function(c,f){var g=this.$element.find(".item.active"),h=f||this.getItemForDirection(c,g),m=this.interval,q="next"==c?"left":"right",x=this;if(h.hasClass("active"))return this.sliding=false;var H=h[0],y=b.Event("slide.bs.carousel",{relatedTarget:H,direction:q});if(this.$element.trigger(y),
!y.isDefaultPrevented()){if(this.sliding=true,m&&this.pause(),this.$indicators.length){this.$indicators.find(".active").removeClass("active");(y=b(this.$indicators.children()[this.getItemIndex(h)]))&&y.addClass("active")}var d=b.Event("slid.bs.carousel",{relatedTarget:H,direction:q});return b.support.transition&&this.$element.hasClass("slide")?(h.addClass(c),g.addClass(q),h.addClass(q),g.one("bsTransitionEnd",function(){h.removeClass([c,q].join(" ")).addClass("active");g.removeClass(["active",q].join(" "));
x.sliding=false;setTimeout(function(){x.$element.trigger(d)},0)}).emulateTransitionEnd(l.TRANSITION_DURATION)):(g.removeClass("active"),h.addClass("active"),this.sliding=false,this.$element.trigger(d)),m&&this.cycle(),this}};var e=b.fn.carousel;b.fn.carousel=j;b.fn.carousel.Constructor=l;b.fn.carousel.noConflict=function(){return b.fn.carousel=e,this};var a=function(c){var f,g=b(this),h=b(g.attr("data-target")||(f=g.attr("href"))&&f.replace(/.*(?=#[^\s]+$)/,""));if(h.hasClass("carousel")){f=b.extend({},
h.data(),g.data());(g=g.attr("data-slide-to"))&&(f.interval=false);j.call(h,f);g&&h.data("bs.carousel").to(g);c.preventDefault()}};b(document).on("click.bs.carousel.data-api","[data-slide]",a).on("click.bs.carousel.data-api","[data-slide-to]",a);b(window).on("load",function(){b('[data-ride="carousel"]').each(function(){var c=b(this);j.call(c,c.data())})})})(jQuery);
(function(b){function j(g){g&&3===g.which||(b(e).remove(),b(a).each(function(){var h=b(this),m=l(h),q={relatedTarget:this};m.hasClass("open")&&(m.trigger(g=b.Event("hide.bs.dropdown",q)),g.isDefaultPrevented()||(h.attr("aria-expanded","false"),m.removeClass("open").trigger("hidden.bs.dropdown",q)))}))}function l(g){var h=g.attr("data-target");h||(h=g.attr("href"),h=h&&/#[A-Za-z]/.test(h)&&h.replace(/.*(?=#[^\s]*$)/,""));return(h=h&&b(h))&&h.length?h:g.parent()}var e=".dropdown-backdrop",a='[data-toggle="dropdown"]',
c=function(g){b(g).on("click.bs.dropdown",this.toggle)};c.VERSION="3.3.2";c.prototype.toggle=function(g){var h=b(this);if(!h.is(".disabled, :disabled")){var m=l(h),q=m.hasClass("open");if(j(),!q){"ontouchstart"in document.documentElement&&!m.closest(".navbar-nav").length&&b('<div class="dropdown-backdrop"></div>').insertAfter(b(this)).on("click",j);q={relatedTarget:this};if(m.trigger(g=b.Event("show.bs.dropdown",q)),g.isDefaultPrevented())return;h.trigger("focus").attr("aria-expanded","true");m.toggleClass("open").trigger("shown.bs.dropdown",
q)}return false}};c.prototype.keydown=function(g){if(/(38|40|27|32)/.test(g.which)&&!/input|textarea/i.test(g.target.tagName)){var h=b(this);if(g.preventDefault(),g.stopPropagation(),!h.is(".disabled, :disabled")){var m=l(h),q=m.hasClass("open");if(!q&&27!=g.which||q&&27==g.which)return 27==g.which&&m.find(a).trigger("focus"),h.trigger("click");h=m.find('[role="menu"] li:not(.disabled):visible a, [role="listbox"] li:not(.disabled):visible a');if(h.length){m=h.index(g.target);38==g.which&&m>0&&m--;
40==g.which&&m<h.length-1&&m++;~m||(m=0);h.eq(m).trigger("focus")}}}};var f=b.fn.dropdown;b.fn.dropdown=function(g){return this.each(function(){var h=b(this),m=h.data("bs.dropdown");m||h.data("bs.dropdown",m=new c(this));"string"==typeof g&&m[g].call(h)})};b.fn.dropdown.Constructor=c;b.fn.dropdown.noConflict=function(){return b.fn.dropdown=f,this};b(document).on("click.bs.dropdown.data-api",j).on("click.bs.dropdown.data-api",".dropdown form",function(g){g.stopPropagation()}).on("click.bs.dropdown.data-api",
a,c.prototype.toggle).on("keydown.bs.dropdown.data-api",a,c.prototype.keydown).on("keydown.bs.dropdown.data-api",'[role="menu"]',c.prototype.keydown).on("keydown.bs.dropdown.data-api",'[role="listbox"]',c.prototype.keydown)})(jQuery);
(function(b){function j(a,c){return this.each(function(){var f=b(this),g=f.data("bs.modal"),h=b.extend({},l.DEFAULTS,f.data(),"object"==typeof a&&a);g||f.data("bs.modal",g=new l(this,h));"string"==typeof a?g[a](c):h.show&&g.show(c)})}var l=function(a,c){this.options=c;this.$body=b(document.body);this.$element=b(a);this.$dialog=this.$element.find(".modal-dialog");this.originalBodyPad=this.isShown=this.$backdrop=null;this.scrollbarWidth=0;this.ignoreBackdropClick=false;this.options.remote&&this.$element.find(".modal-content").load(this.options.remote,
b.proxy(function(){this.$element.trigger("loaded.bs.modal")},this))};l.VERSION="3.3.2";l.TRANSITION_DURATION=300;l.BACKDROP_TRANSITION_DURATION=150;l.DEFAULTS={backdrop:true,keyboard:true,show:true};l.prototype.toggle=function(a){return this.isShown?this.hide():this.show(a)};l.prototype.show=function(a){var c=this,f=b.Event("show.bs.modal",{relatedTarget:a});this.$element.trigger(f);this.isShown||f.isDefaultPrevented()||(this.isShown=true,this.checkScrollbar(),this.setScrollbar(),this.$body.addClass("modal-open"),
this.escape(),this.resize(),this.$element.on("click.dismiss.bs.modal",'[data-dismiss="modal"]',b.proxy(this.hide,this)),this.$dialog.on("mousedown.dismiss.bs.modal",function(){c.$element.one("mouseup.dismiss.bs.modal",function(g){b(g.target).is(c.$element)&&(c.ignoreBackdropClick=true)})}),this.backdrop(function(){var g=b.support.transition&&c.$element.hasClass("fade");c.$element.parent().length||c.$element.appendTo(c.$body);c.$element.show().scrollTop(0);c.adjustDialog();c.$element.addClass("in").attr("aria-hidden",
false);c.enforceFocus();var h=b.Event("shown.bs.modal",{relatedTarget:a});g?c.$dialog.one("bsTransitionEnd",function(){c.$element.trigger("focus").trigger(h)}).emulateTransitionEnd(l.TRANSITION_DURATION):c.$element.trigger("focus").trigger(h)}))};l.prototype.hide=function(a){a&&a.preventDefault();a=b.Event("hide.bs.modal");this.$element.trigger(a);this.isShown&&!a.isDefaultPrevented()&&(this.isShown=false,this.escape(),this.resize(),b(document).off("focusin.bs.modal"),this.$element.removeClass("in").attr("aria-hidden",
true).off("click.dismiss.bs.modal").off("mouseup.dismiss.bs.modal"),this.$dialog.off("mousedown.dismiss.bs.modal"),b.support.transition&&this.$element.hasClass("fade")?this.$element.one("bsTransitionEnd",b.proxy(this.hideModal,this)).emulateTransitionEnd(l.TRANSITION_DURATION):this.hideModal())};l.prototype.enforceFocus=function(){b(document).off("focusin.bs.modal").on("focusin.bs.modal",b.proxy(function(a){this.$element[0]===a.target||this.$element.has(a.target).length||this.$element.trigger("focus")},
this))};l.prototype.escape=function(){this.isShown&&this.options.keyboard?this.$element.on("keydown.dismiss.bs.modal",b.proxy(function(a){27==a.which&&this.hide()},this)):this.isShown||this.$element.off("keydown.dismiss.bs.modal")};l.prototype.resize=function(){this.isShown?b(window).on("resize.bs.modal",b.proxy(this.handleUpdate,this)):b(window).off("resize.bs.modal")};l.prototype.hideModal=function(){var a=this;this.$element.hide();this.backdrop(function(){a.$body.removeClass("modal-open");a.resetAdjustments();
a.resetScrollbar();a.$element.trigger("hidden.bs.modal")})};l.prototype.removeBackdrop=function(){this.$backdrop&&this.$backdrop.remove();this.$backdrop=null};l.prototype.backdrop=function(a){var c=this,f=this.$element.hasClass("fade")?"fade":"";if(this.isShown&&this.options.backdrop){var g=b.support.transition&&f;if(!(this.$backdrop=b('<div class="modal-backdrop '+f+'" ></h>').appendTo(this.$body),this.$element.on("click.dismiss.bs.modal",b.proxy(function(h){return this.ignoreBackdropClick?void(this.ignoreBackdropClick=
false):void(h.target===h.currentTarget&&("static"==this.options.backdrop?this.$element[0].focus():this.hide()))},this)),this.$backdrop.addClass("in"),!a))g?this.$backdrop.one("bsTransitionEnd",a).emulateTransitionEnd(l.BACKDROP_TRANSITION_DURATION):a()}else if(!this.isShown&&this.$backdrop){this.$backdrop.removeClass("in");f=function(){c.removeBackdrop();a&&a()};b.support.transition&&this.$element.hasClass("fade")?this.$backdrop.one("bsTransitionEnd",f).emulateTransitionEnd(l.BACKDROP_TRANSITION_DURATION):
f()}else a&&a()};l.prototype.handleUpdate=function(){this.adjustDialog()};l.prototype.adjustDialog=function(){var a=this.$element[0].scrollHeight>document.documentElement.clientHeight;this.$element.css({paddingLeft:!this.bodyIsOverflowing&&a?this.scrollbarWidth:"",paddingRight:this.bodyIsOverflowing&&!a?this.scrollbarWidth:""})};l.prototype.resetAdjustments=function(){this.$element.css({paddingLeft:"",paddingRight:""})};l.prototype.checkScrollbar=function(){var a=window.innerWidth;if(!a){a=document.documentElement.getBoundingClientRect();
a=a.right-Math.abs(a.left)}this.bodyIsOverflowing=document.body.clientWidth<a;this.scrollbarWidth=this.measureScrollbar()};l.prototype.setScrollbar=function(){var a=parseInt(this.$body.css("padding-right")||0,10);this.originalBodyPad=document.body.style.paddingRight||"";this.bodyIsOverflowing&&this.$body.css("padding-right",a+this.scrollbarWidth)};l.prototype.resetScrollbar=function(){this.$body.css("padding-right",this.originalBodyPad)};l.prototype.measureScrollbar=function(){var a=document.createElement("div");
a.className="modal-scrollbar-measure";this.$body.append(a);var c=a.offsetWidth-a.clientWidth;return this.$body[0].removeChild(a),c};var e=b.fn.modal;b.fn.modal=j;b.fn.modal.Constructor=l;b.fn.modal.noConflict=function(){return b.fn.modal=e,this};b(document).on("click.bs.modal.data-api",'[data-toggle="modal"]',function(a){var c=b(this),f=c.attr("href"),g=b(c.attr("data-target")||f&&f.replace(/.*(?=#[^\s]+$)/,""));f=g.data("bs.modal")?"toggle":b.extend({remote:!/#/.test(f)&&f},g.data(),c.data());c.is("a")&&
a.preventDefault();g.one("show.bs.modal",function(h){h.isDefaultPrevented()||g.one("hidden.bs.modal",function(){c.is(":visible")&&c.trigger("focus")})});j.call(g,f,this)})})(jQuery);
(function(b){var j=function(e,a){this.$element=this.hoverState=this.timeout=this.enabled=this.options=this.type=null;this.init("tooltip",e,a)};j.VERSION="3.3.2";j.TRANSITION_DURATION=150;j.DEFAULTS={animation:true,placement:"top",selector:false,template:'<div class="tooltip" role="tooltip"><div class="tooltip-arrow"></div><div class="tooltip-inner"></div></div>',trigger:"hover focus",title:"",delay:0,html:false,container:false,viewport:{selector:"body",padding:0}};j.prototype.init=function(e,a,c){if(this.enabled=
true,this.type=e,this.$element=b(a),this.options=this.getOptions(c),this.$viewport=this.options.viewport&&b(this.options.viewport.selector||this.options.viewport),this.$element[0]instanceof document.constructor&&!this.options.selector)throw Error("`selector` option must be specified when initializing "+this.type+" on the window.document object!");e=this.options.trigger.split(" ");for(a=e.length;a--;){c=e[a];if("click"==c)this.$element.on("click."+this.type,this.options.selector,b.proxy(this.toggle,
this));else if("manual"!=c){var f="hover"==c?"mouseleave":"focusout";this.$element.on(("hover"==c?"mouseenter":"focusin")+"."+this.type,this.options.selector,b.proxy(this.enter,this));this.$element.on(f+"."+this.type,this.options.selector,b.proxy(this.leave,this))}}this.options.selector?this._options=b.extend({},this.options,{trigger:"manual",selector:""}):this.fixTitle()};j.prototype.getDefaults=function(){return j.DEFAULTS};j.prototype.getOptions=function(e){return e=b.extend({},this.getDefaults(),
this.$element.data(),e),e.delay&&"number"==typeof e.delay&&(e.delay={show:e.delay,hide:e.delay}),e};j.prototype.getDelegateOptions=function(){var e={},a=this.getDefaults();return this._options&&b.each(this._options,function(c,f){a[c]!=f&&(e[c]=f)}),e};j.prototype.enter=function(e){var a=e instanceof this.constructor?e:b(e.currentTarget).data("bs."+this.type);return a&&a.$tip&&a.$tip.is(":visible")?void(a.hoverState="in"):(a||(a=new this.constructor(e.currentTarget,this.getDelegateOptions()),b(e.currentTarget).data("bs."+
this.type,a)),clearTimeout(a.timeout),a.hoverState="in",a.options.delay&&a.options.delay.show?void(a.timeout=setTimeout(function(){"in"==a.hoverState&&a.show()},a.options.delay.show)):a.show())};j.prototype.leave=function(e){var a=e instanceof this.constructor?e:b(e.currentTarget).data("bs."+this.type);return a||(a=new this.constructor(e.currentTarget,this.getDelegateOptions()),b(e.currentTarget).data("bs."+this.type,a)),clearTimeout(a.timeout),a.hoverState="out",a.options.delay&&a.options.delay.hide?
void(a.timeout=setTimeout(function(){"out"==a.hoverState&&a.hide()},a.options.delay.hide)):a.hide()};j.prototype.show=function(){var e=b.Event("show.bs."+this.type);if(this.hasContent()&&this.enabled){this.$element.trigger(e);var a=b.contains(this.$element[0].ownerDocument.documentElement,this.$element[0]);if(!(e.isDefaultPrevented()||!a)){var c=this;e=this.tip();a=this.getUID(this.type);this.setContent();e.attr("id",a);this.$element.attr("aria-describedby",a);this.options.animation&&e.addClass("fade");
a="function"==typeof this.options.placement?this.options.placement.call(this,e[0],this.$element[0]):this.options.placement;var f=/\s?auto?\s?/i,g=f.test(a);g&&(a=a.replace(f,"")||"top");e.detach().css({top:0,left:0,display:"block"}).addClass(a).data("bs."+this.type,this);this.options.container?e.appendTo(this.options.container):e.insertAfter(this.$element);f=this.getPosition();var h=e[0].offsetWidth,m=e[0].offsetHeight;if(g){g=a;var q=this.getPosition(this.options.container?b(this.options.container):
this.$element.parent());a="bottom"==a&&f.bottom+m>q.bottom?"top":"top"==a&&f.top-m<q.top?"bottom":"right"==a&&f.right+h>q.width?"left":"left"==a&&f.left-h<q.left?"right":a;e.removeClass(g).addClass(a)}this.applyPlacement(this.getCalculatedOffset(a,f,h,m),a);a=function(){var x=c.hoverState;c.$element.trigger("shown.bs."+c.type);c.hoverState=null;"out"==x&&c.leave(c)};b.support.transition&&this.$tip.hasClass("fade")?e.one("bsTransitionEnd",a).emulateTransitionEnd(j.TRANSITION_DURATION):a()}}};j.prototype.applyPlacement=
function(e,a){var c=this.tip(),f=c[0].offsetWidth,g=c[0].offsetHeight,h=parseInt(c.css("margin-top"),10),m=parseInt(c.css("margin-left"),10);isNaN(h)&&(h=0);isNaN(m)&&(m=0);e.top+=h;e.left+=m;b.offset.setOffset(c[0],b.extend({using:function(H){c.css({top:Math.round(H.top),left:Math.round(H.left)})}},e),0);c.addClass("in");m=c[0].offsetWidth;var q=c[0].offsetHeight;"top"==a&&q!=g&&(e.top=e.top+g-q);var x=this.getViewportAdjustedDelta(a,e,m,q);x.left?e.left+=x.left:e.top+=x.top;f=(h=/top|bottom/.test(a))?
2*x.left-f+m:2*x.top-g+q;g=h?"offsetWidth":"offsetHeight";c.offset(e);this.replaceArrow(f,c[0][g],h)};j.prototype.replaceArrow=function(e,a,c){this.arrow().css(c?"left":"top",50*(1-e/a)+"%").css(c?"top":"left","")};j.prototype.setContent=function(){var e=this.tip(),a=this.getTitle();e.find(".tooltip-inner")[this.options.html?"html":"text"](a);e.removeClass("fade in top bottom left right")};j.prototype.hide=function(e){function a(){"in"!=c.hoverState&&f.detach();c.$element.removeAttr("aria-describedby").trigger("hidden.bs."+
c.type);e&&e()}var c=this,f=b(this.$tip),g=b.Event("hide.bs."+this.type);return this.$element.trigger(g),g.isDefaultPrevented()?void 0:(f.removeClass("in"),b.support.transition&&f.hasClass("fade")?f.one("bsTransitionEnd",a).emulateTransitionEnd(j.TRANSITION_DURATION):a(),this.hoverState=null,this)};j.prototype.fixTitle=function(){var e=this.$element;(e.attr("title")||"string"!=typeof e.attr("data-original-title"))&&e.attr("data-original-title",e.attr("title")||"").attr("title","")};j.prototype.hasContent=
function(){return this.getTitle()};j.prototype.getPosition=function(e){e=e||this.$element;var a=e[0],c="BODY"==a.tagName;a=a.getBoundingClientRect();null==a.width&&(a=b.extend({},a,{width:a.right-a.left,height:a.bottom-a.top}));var f=c?{top:0,left:0}:e.offset();e={scroll:c?document.documentElement.scrollTop||document.body.scrollTop:e.scrollTop()};c=c?{width:b(window).width(),height:b(window).height()}:null;return b.extend({},a,e,c,f)};j.prototype.getCalculatedOffset=function(e,a,c,f){return"bottom"==
e?{top:a.top+a.height,left:a.left+a.width/2-c/2}:"top"==e?{top:a.top-f,left:a.left+a.width/2-c/2}:"left"==e?{top:a.top+a.height/2-f/2,left:a.left-c}:{top:a.top+a.height/2-f/2,left:a.left+a.width}};j.prototype.getViewportAdjustedDelta=function(e,a,c,f){var g={top:0,left:0};if(!this.$viewport)return g;var h=this.options.viewport&&this.options.viewport.padding||0,m=this.getPosition(this.$viewport);if(/right|left/.test(e)){c=a.top-h-m.scroll;a=a.top+h-m.scroll+f;c<m.top?g.top=m.top-c:a>m.top+m.height&&
(g.top=m.top+m.height-a)}else{f=a.left-h;a=a.left+h+c;f<m.left?g.left=m.left-f:a>m.width&&(g.left=m.left+m.width-a)}return g};j.prototype.getTitle=function(){var e=this.$element,a=this.options;return e.attr("data-original-title")||("function"==typeof a.title?a.title.call(e[0]):a.title)};j.prototype.getUID=function(e){do e+=~~(1E6*Math.random());while(document.getElementById(e));return e};j.prototype.tip=function(){return this.$tip=this.$tip||b(this.options.template)};j.prototype.arrow=function(){return this.$arrow=
this.$arrow||this.tip().find(".tooltip-arrow")};j.prototype.enable=function(){this.enabled=true};j.prototype.disable=function(){this.enabled=false};j.prototype.toggleEnabled=function(){this.enabled=!this.enabled};j.prototype.toggle=function(e){var a=this;e&&(a=b(e.currentTarget).data("bs."+this.type),a||(a=new this.constructor(e.currentTarget,this.getDelegateOptions()),b(e.currentTarget).data("bs."+this.type,a)));a.tip().hasClass("in")?a.leave(a):a.enter(a)};j.prototype.destroy=function(){var e=this;
clearTimeout(this.timeout);this.hide(function(){e.$element.off("."+e.type).removeData("bs."+e.type)})};var l=b.fn.tooltip;b.fn.tooltip=function(e){return this.each(function(){var a=b(this),c=a.data("bs.tooltip"),f="object"==typeof e&&e;(c||!/destroy|hide/.test(e))&&(c||a.data("bs.tooltip",c=new j(this,f)),"string"==typeof e&&c[e]())})};b.fn.tooltip.Constructor=j;b.fn.tooltip.noConflict=function(){return b.fn.tooltip=l,this}})(jQuery);
(function(b){var j=function(e,a){this.init("popover",e,a)};if(!b.fn.tooltip)throw Error("Popover requires tooltip.js");j.VERSION="3.3.2";j.DEFAULTS=b.extend({},b.fn.tooltip.Constructor.DEFAULTS,{placement:"right",trigger:"click",content:"",template:'<div class="popover" role="tooltip"><div class="arrow"></div><h3 class="popover-title"></h3><div class="popover-content"></div></div>'});j.prototype=b.extend({},b.fn.tooltip.Constructor.prototype);j.prototype.constructor=j;j.prototype.getDefaults=function(){return j.DEFAULTS};
j.prototype.setContent=function(){var e=this.tip(),a=this.getTitle(),c=this.getContent();e.find(".popover-title")[this.options.html?"html":"text"](a);e.find(".popover-content").children().detach().end()[this.options.html?"string"==typeof c?"html":"append":"text"](c);e.removeClass("fade top bottom left right in");e.find(".popover-title").html()||e.find(".popover-title").hide()};j.prototype.hasContent=function(){return this.getTitle()||this.getContent()};j.prototype.getContent=function(){var e=this.$element,
a=this.options;return e.attr("data-content")||("function"==typeof a.content?a.content.call(e[0]):a.content)};j.prototype.arrow=function(){return this.$arrow=this.$arrow||this.tip().find(".arrow")};var l=b.fn.popover;b.fn.popover=function(e){return this.each(function(){var a=b(this),c=a.data("bs.popover"),f="object"==typeof e&&e;(c||!/destroy|hide/.test(e))&&(c||a.data("bs.popover",c=new j(this,f)),"string"==typeof e&&c[e]())})};b.fn.popover.Constructor=j;b.fn.popover.noConflict=function(){return b.fn.popover=
l,this}})(jQuery);
(function(b){function j(c){return this.each(function(){var f=b(this),g=f.data("bs.tab");g||f.data("bs.tab",g=new l(this));"string"==typeof c&&g[c]()})}var l=function(c){this.element=b(c)};l.VERSION="3.3.2";l.TRANSITION_DURATION=150;l.prototype.show=function(){var c=this.element,f=c.closest("ul:not(.dropdown-menu)"),g=c.data("target");if(g||(g=c.attr("href"),g=g&&g.replace(/.*(?=#[^\s]*$)/,"")),!c.parent("li").hasClass("active")){var h=f.find(".active:last a"),m=b.Event("hide.bs.tab",{relatedTarget:c[0]}),
q=b.Event("show.bs.tab",{relatedTarget:h[0]});if(h.trigger(m),c.trigger(q),!q.isDefaultPrevented()&&!m.isDefaultPrevented()){g=b(g);this.activate(c.closest("li"),f);this.activate(g,g.parent(),function(){h.trigger({type:"hidden.bs.tab",relatedTarget:c[0]});c.trigger({type:"shown.bs.tab",relatedTarget:h[0]})})}}};l.prototype.activate=function(c,f,g){function h(){m.removeClass("active").find("> .dropdown-menu > .active").removeClass("active").end().find('[data-toggle="tab"]').attr("aria-expanded",false);
c.addClass("active").find('[data-toggle="tab"]').attr("aria-expanded",true);q?c.addClass("in"):c.removeClass("fade");c.parent(".dropdown-menu").length&&c.closest("li.dropdown").addClass("active").end().find('[data-toggle="tab"]').attr("aria-expanded",true);g&&g()}var m=f.find("> .active"),q=g&&b.support.transition&&(m.length&&m.hasClass("fade")||!!f.find("> .fade").length);m.length&&q?m.one("bsTransitionEnd",h).emulateTransitionEnd(l.TRANSITION_DURATION):h();m.removeClass("in")};var e=b.fn.tab;b.fn.tab=
j;b.fn.tab.Constructor=l;b.fn.tab.noConflict=function(){return b.fn.tab=e,this};var a=function(c){c.preventDefault();j.call(b(this),"show")};b(document).on("click.bs.tab.data-api",'[data-toggle="tab"]',a).on("click.bs.tab.data-api",'[data-toggle="pill"]',a)})(jQuery);
(function(b){function j(a){return this.each(function(){var c=b(this),f=c.data("bs.affix"),g="object"==typeof a&&a;f||c.data("bs.affix",f=new l(this,g));"string"==typeof a&&f[a]()})}var l=function(a,c){this.options=b.extend({},l.DEFAULTS,c);this.$target=b(this.options.target).on("scroll.bs.affix.data-api",b.proxy(this.checkPosition,this)).on("click.bs.affix.data-api",b.proxy(this.checkPositionWithEventLoop,this));this.$element=b(a);this.pinnedOffset=this.unpin=this.affixed=null;this.checkPosition()};
l.VERSION="3.3.2";l.RESET="affix affix-top affix-bottom";l.DEFAULTS={offset:0,target:window};l.prototype.getState=function(a,c,f,g){var h=this.$target.scrollTop(),m=this.$element.offset(),q=this.$target.height();if(null!=f&&"top"==this.affixed)return f>h?"top":false;if("bottom"==this.affixed)return null!=f?h+this.unpin<=m.top?false:"bottom":a-g>=h+q?false:"bottom";var x=null==this.affixed;m=x?h:m.top;return null!=f&&f>=h?"top":null!=g&&m+(x?q:c)>=a-g?"bottom":false};l.prototype.getPinnedOffset=function(){if(this.pinnedOffset)return this.pinnedOffset;
this.$element.removeClass(l.RESET).addClass("affix");var a=this.$target.scrollTop();return this.pinnedOffset=this.$element.offset().top-a};l.prototype.checkPositionWithEventLoop=function(){setTimeout(b.proxy(this.checkPosition,this),1)};l.prototype.checkPosition=function(){if(this.$element.is(":visible")){var a=this.$element.height(),c=this.options.offset,f=c.top,g=c.bottom,h=b(document.body).height();"object"!=typeof c&&(g=f=c);"function"==typeof f&&(f=c.top(this.$element));"function"==typeof g&&
(g=c.bottom(this.$element));c=this.getState(h,a,f,g);if(this.affixed!=c){null!=this.unpin&&this.$element.css("top","");f="affix"+(c?"-"+c:"");var m=b.Event(f+".bs.affix");if(this.$element.trigger(m),m.isDefaultPrevented())return;this.affixed=c;this.unpin="bottom"==c?this.getPinnedOffset():null;this.$element.removeClass(l.RESET).addClass(f).trigger(f.replace("affix","affixed")+".bs.affix")}"bottom"==c&&this.$element.offset({top:h-a-g})}};var e=b.fn.affix;b.fn.affix=j;b.fn.affix.Constructor=l;b.fn.affix.noConflict=
function(){return b.fn.affix=e,this};b(window).on("load",function(){b('[data-spy="affix"]').each(function(){var a=b(this),c=a.data();c.offset=c.offset||{};null!=c.offsetBottom&&(c.offset.bottom=c.offsetBottom);null!=c.offsetTop&&(c.offset.top=c.offsetTop);j.call(a,c)})})})(jQuery);
(function(b){function j(c){var f;c=c.attr("data-target")||(f=c.attr("href"))&&f.replace(/.*(?=#[^\s]+$)/,"");return b(c)}function l(c){return this.each(function(){var f=b(this),g=f.data("bs.collapse"),h=b.extend({},e.DEFAULTS,f.data(),"object"==typeof c&&c);!g&&h.toggle&&/show|hide/.test(c)&&(h.toggle=false);g||f.data("bs.collapse",g=new e(this,h));"string"==typeof c&&g[c]()})}var e=function(c,f){this.$element=b(c);this.options=b.extend({},e.DEFAULTS,f);this.$trigger=b('[data-toggle="collapse"][href="#'+
c.id+'"],[data-toggle="collapse"][data-target="#'+c.id+'"]');this.transitioning=null;this.options.parent?this.$parent=this.getParent():this.addAriaAndCollapsedClass(this.$element,this.$trigger);this.options.toggle&&this.toggle()};e.VERSION="3.3.2";e.TRANSITION_DURATION=350;e.DEFAULTS={toggle:true};e.prototype.dimension=function(){return this.$element.hasClass("width")?"width":"height"};e.prototype.show=function(){if(!this.transitioning&&!this.$element.hasClass("in")){var c,f=this.$parent&&this.$parent.children(".panel").children(".in, .collapsing");
if(!(f&&f.length&&(c=f.data("bs.collapse"),c&&c.transitioning))){var g=b.Event("show.bs.collapse");if(this.$element.trigger(g),!g.isDefaultPrevented()){f&&f.length&&(l.call(f,"hide"),c||f.data("bs.collapse",null));var h=this.dimension();this.$element.removeClass("collapse").addClass("collapsing")[h](0).attr("aria-expanded",true);this.$trigger.removeClass("collapsed").attr("aria-expanded",true);this.transitioning=1;c=function(){this.$element.removeClass("collapsing").addClass("collapse in")[h]("");
this.transitioning=0;this.$element.trigger("shown.bs.collapse")};if(!b.support.transition)return c.call(this);f=b.camelCase(["scroll",h].join("-"));this.$element.one("bsTransitionEnd",b.proxy(c,this)).emulateTransitionEnd(e.TRANSITION_DURATION)[h](this.$element[0][f])}}}};e.prototype.hide=function(){if(!this.transitioning&&this.$element.hasClass("in")){var c=b.Event("hide.bs.collapse");if(this.$element.trigger(c),!c.isDefaultPrevented()){c=this.dimension();this.$element[c](this.$element[c]());this.$element.addClass("collapsing").removeClass("collapse in").attr("aria-expanded",
false);this.$trigger.addClass("collapsed").attr("aria-expanded",false);this.transitioning=1;var f=function(){this.transitioning=0;this.$element.removeClass("collapsing").addClass("collapse").trigger("hidden.bs.collapse")};return b.support.transition?void this.$element[c](0).one("bsTransitionEnd",b.proxy(f,this)).emulateTransitionEnd(e.TRANSITION_DURATION):f.call(this)}}};e.prototype.toggle=function(){this[this.$element.hasClass("in")?"hide":"show"]()};e.prototype.getParent=function(){return b(this.options.parent).find('[data-toggle="collapse"][data-parent="'+
this.options.parent+'"]').each(b.proxy(function(c,f){var g=b(f);this.addAriaAndCollapsedClass(j(g),g)},this)).end()};e.prototype.addAriaAndCollapsedClass=function(c,f){var g=c.hasClass("in");c.attr("aria-expanded",g);f.toggleClass("collapsed",!g).attr("aria-expanded",g)};var a=b.fn.collapse;b.fn.collapse=l;b.fn.collapse.Constructor=e;b.fn.collapse.noConflict=function(){return b.fn.collapse=a,this};b(document).on("click.bs.collapse.data-api",'[data-toggle="collapse"]',function(c){var f=b(this);f.attr("data-target")||
c.preventDefault();c=j(f);f=c.data("bs.collapse")?"toggle":f.data();l.call(c,f)})})(jQuery);
(function(b){function j(a,c){this.$body=b(document.body);this.$scrollElement=b(b(a).is(document.body)?window:a);this.options=b.extend({},j.DEFAULTS,c);this.selector=(this.options.target||"")+" .nav li > a";this.offsets=[];this.targets=[];this.activeTarget=null;this.scrollHeight=0;this.$scrollElement.on("scroll.bs.scrollspy",b.proxy(this.process,this));this.refresh();this.process()}function l(a){return this.each(function(){var c=b(this),f=c.data("bs.scrollspy"),g="object"==typeof a&&a;f||c.data("bs.scrollspy",
f=new j(this,g));"string"==typeof a&&f[a]()})}j.VERSION="3.3.2";j.DEFAULTS={offset:10};j.prototype.getScrollHeight=function(){return this.$scrollElement[0].scrollHeight||Math.max(this.$body[0].scrollHeight,document.documentElement.scrollHeight)};j.prototype.refresh=function(){var a=this,c="offset",f=0;this.offsets=[];this.targets=[];this.scrollHeight=this.getScrollHeight();b.isWindow(this.$scrollElement[0])||(c="position",f=this.$scrollElement.scrollTop());this.$body.find(this.selector).map(function(){var g=
b(this);g=g.data("target")||g.attr("href");var h=/^#./.test(g)&&b(g);return h&&h.length&&h.is(":visible")&&[[h[c]().top+f,g]]||null}).sort(function(g,h){return g[0]-h[0]}).each(function(){a.offsets.push(this[0]);a.targets.push(this[1])})};j.prototype.process=function(){var a,c=this.$scrollElement.scrollTop()+this.options.offset,f=this.getScrollHeight(),g=this.options.offset+f-this.$scrollElement.height(),h=this.offsets,m=this.targets,q=this.activeTarget;if(this.scrollHeight!=f&&this.refresh(),c>=
g)return q!=(a=m[m.length-1])&&this.activate(a);if(q&&c<h[0])return this.activeTarget=null,this.clear();for(a=h.length;a--;)q!=m[a]&&c>=h[a]&&(void 0===h[a+1]||c<=h[a+1])&&this.activate(m[a])};j.prototype.activate=function(a){this.activeTarget=a;this.clear();a=b(this.selector+'[data-target="'+a+'"],'+this.selector+'[href="'+a+'"]').parents("li").addClass("active");a.parent(".dropdown-menu").length&&(a=a.closest("li.dropdown").addClass("active"));a.trigger("activate.bs.scrollspy")};j.prototype.clear=
function(){b(this.selector).parentsUntil(this.options.target,".active").removeClass("active")};var e=b.fn.scrollspy;b.fn.scrollspy=l;b.fn.scrollspy.Constructor=j;b.fn.scrollspy.noConflict=function(){return b.fn.scrollspy=e,this};b(window).on("load.bs.scrollspy.data-api",function(){b('[data-spy="scroll"]').each(function(){var a=b(this);l.call(a,a.data())})})})(jQuery);
(function(b){function j(){var l=document.createElement("bootstrap"),e={WebkitTransition:"webkitTransitionEnd",MozTransition:"transitionend",OTransition:"oTransitionEnd otransitionend",transition:"transitionend"},a;for(a in e)if(void 0!==l.style[a])return{end:e[a]};return false}b.fn.emulateTransitionEnd=function(l){var e=false,a=this;b(this).one("bsTransitionEnd",function(){e=true});return setTimeout(function(){e||b(a).trigger(b.support.transition.end)},l),this};b(function(){b.support.transition=j();
b.support.transition&&(b.event.special.bsTransitionEnd={bindType:b.support.transition.end,delegateType:b.support.transition.end,handle:function(l){return b(l.target).is(this)?l.handleObj.handler.apply(this,arguments):void 0}})})})(jQuery);
